[package]
name = "streamlit"
version = "0.1.0"
edition = "2024"
authors = ["killf <killf@foxmail.com>"]
description = "The rust version of streamlit"
repository = "https://github.com/killf/streamlit-rust"
readme = "README.md"

[dependencies]
